builders:
  swagger_generator:
    import: "package:swagger_generator_flutter/swagger_generator_flutter.dart"
    builder_factories: ["swaggerBuilder"]
    auto_apply: dependents
    build_to: source
    runs_before:
      - "json_serializable:json_serializable"
      - "chopper_generator:chopper_generator"
